config/routes.rb
Rails.application.routes.draw do
  # namespace :manager do
  #     devise_for :admin_users, controllers: {
  #     sessions: 'manager/admin_users/sessions',
  #     registrations: 'manager/admin_users/registrations',
  #     passwords: 'manager/admin_users/passwords'
  #   }
  # end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  scope module: 'site' do
    resources :post_images do
      resources :answers, only: [:create, :show]
      get 'like', to: 'favorites#like'
      get 'unlike', to: 'favorites#unlike'
    end
    resources :game_records, only: [:new, :create, :update, :destroy]
    resources :selections
    resources :answers
    resources :post_comments
    resources :reports, only: [:show]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      resources :reports, only: [:create]
      get 'created', to: 'post_images#created'
      get 'selected', to: 'post_images#selected'
      get 'fav_nanikiru', to: 'favorites#nanikiru'
      get 'following', to: 'users#following_index'
      get 'follower', to: 'users#follower_index'
      get 'follow_nanikiru', to: 'users#follow_nanikiru'
    end
    resources :relationships, only: [:create, :destroy]
    root to: 'users#welcome'
    get 'nanikiru_all', to: 'post_images#index_all'
    get 'nanikiru_4p', to: 'post_images#index_4p'
    get 'nanikiru_3p', to: 'post_images#index_3p'
    get 'nanikiru_other', to: 'post_images#index_other'
  end
end

app/models/site.rb
module Site
  def self.table_name_prefix
    'site_'
  end
end

app/controllers/site/answers_controller.rb
class Site::AnswersController < Site::Base
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = Answer.all
  end



  def show
    @answer = Answer.find(params[:id])
    @post_image = PostImage.find(params[:post_image_id])
    @post_comment = PostComment.new
    @selections = @post_image.selections
    # post_imagesに対するcommentsをidが古い順に抽出
    comments = @answer.post_image_comments(@post_image)
    @comments = Kaminari.paginate_array(comments).page(params[:page]).per(50)
  end

  def new
  end

  def edit
  end

  def create
     @post_image = PostImage.find(params[:post_image_id])
     # 重複した選択肢を削除する
     current_user.same_answer_destroy
    # 回答済みのNanikiruかどうか
    if @post_image.answered?(current_user)
      # 回答済みのユーザーは回答出来ずに結果画面にリダイレクトする
        if answered_id = @post_image.answered_id(current_user)
          flash[:danger] = '回答済みのNanikiruです！！'
          redirect_to post_image_answer_path(@post_image.id,answered_id)
        else
          flash[:danger] = '[Error!]回答に問題があります'
          redirect_to root_path
        end
      else
      # 回答済みのではない場合save
      @answer = Answer.new(answer_params)
      @answer.user_id = current_user.id
      respond_to do |format|
        if @answer.save
          format.html { redirect_to post_image_answer_path(params[:post_image_id],@answer.id), notice: 'Answer was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :selection_id)
    end
end

app/controllers/site/base.rb
class Site::Base < ApplicationController
	layout 'site'
end

app/controllers/site/favorites_controller.rb
class Site::FavoritesController < Site::Base
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  def nanikiru
   @user = User.find(params[:user_id])
   @favorites = @user.favorites
  end


  def create
    redirect_back(fallback_location:root_path)
  end

  def destroy
    @favorite.destroy
    # respond_to do |format|
    #   format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
    # end
  end

  def like
    @post_image = PostImage.find(params[:post_image_id])
    current_user.like(@post_image)
    redirect_back(fallback_location:root_path)
  end

  def unlike
    @post_image = PostImage.find(params[:post_image_id])
    current_user.unlike(@post_image)
    redirect_back(fallback_location:root_path)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :post_image_id)
    end
end

app/controllers/site/game_records_controller.rb
class Site::GameRecordsController < Site::Base
  before_action :set_game_record, only: [:show, :edit, :update, :destroy]
  def new
    @game_record = GameRecord.new
  end

  def edit
  end

  def create
    @game_record = GameRecord.new(game_record_params)
    @game_record.user_id = current_user.id
    respond_to do |format|
      if @game_record.save
        format.html { redirect_to user_path(current_user), notice: 'Game record was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @game_record.update(game_record_params)
        format.html { redirect_to user_path(current_user), notice: 'Game record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @game_record.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@game_record.user_id), notice: 'Game record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_record
      @game_record = GameRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_record_params
      params.require(:game_record).permit(:user_id, :handle_name, :game_type, :ability, :game_name)
    end
end

app/controllers/site/homes_controller.rb
class Site::HomesController < Site::Base
  def index
    if session[:user_id].nil?
      redirect_to action:'login'
    else
      @user = User.find(session[:user_id])
    end
  end

  def login
  end
end

app/controllers/site/post_comments_controller.rb
class Site::PostCommentsController < Site::Base
  def create
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.answer_id = params[:answer_id]
    respond_to do |format|
      if @post_comment.save
        format.html { redirect_to post_image_answer_path(@post_comment.answer.selection.post_image_id,@post_comment.answer_id), notice: 'Answer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def destroy
  end
  def new
  end
  private
  def post_comment_params
    params.require(:post_comment).permit(:ansewr_id, :comment)
  end
end

app/controllers/site/post_images_controller.rb
class Site::PostImagesController < Site::Base
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]
  def index
    @post_images = PostImage.page(params[:page]).reverse_order.per(9)
    @post_4p_images = PostImage.where(image_type: "player_4").page(params[:page]).reverse_order.per(9)
    @post_3p_images = PostImage.where(image_type: "player_3").page(params[:page]).reverse_order.per(9)
    @post_other_images = PostImage.where(image_type: "others").page(params[:page]).reverse_order.per(9)
  end

  def index_all
    @post_images = PostImage.page(params[:page]).reverse_order.per(12)
  end

  def index_4p
    @post_4p_images = PostImage.where(image_type: "player_4").page(params[:page]).reverse_order.per(12)
  end

  def index_3p
    @post_3p_images = PostImage.where(image_type: "player_3").page(params[:page]).reverse_order.per(12)
  end

  def index_other
    @post_other_images = PostImage.where(image_type: "others").page(params[:page]).reverse_order.per(12)
  end

  def show
    # 重複した選択肢を削除する
    current_user.same_answer_destroy
    @post_image = PostImage.find(params[:id])
    # selectの削除
    @post_image.selections.where(name: "select").destroy_all
    # 回答済みのユーザーを回答済み画面にリダイレクト
    if @post_image.answered?(current_user)
      answered_id = @post_image.answered_id(current_user)
      if answered_id
        redirect_to post_image_answer_path(@post_image.id,answered_id)
      else
        flash[:danger] = '[Error!]回答が存在しません'
        redirect_to root_path
      end
    end
    @selection = Selection.new
    @answer = Answer.new
    @report = Report.new
  end

  def new
    @post_image = PostImage.new
    @post_image.selections.build
  end

  def edit
    @report = Report.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        else
        format.html { render :new }
      end
    end
    # 選択肢の重複の削除
    @post_image.same_selection_destroy
  end
  # user_created_nanikiruページ
  def created
    @user = User.find(params[:user_id])
    @post_images = @user.post_images
    @report = Report.new
  end
  # user_selected_nanikiru
  def selected
    @user = User.find(params[:user_id])
    @answers = @user.answers
    # 重複した選択肢を削除する
    @user.same_answer_destroy
  end

  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url, notice: 'Post image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    def post_image_params
      params.require(:post_image).permit(:user_id, :image_type, :image, :comment, selections_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/site/relationships_controller.rb
class Site::RelationshipsController < Site::Base
before_action :set_user

  def create
    user = User.find(params[:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:info] = 'ユーザーをフォローしました'
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:info] = 'ユーザーのフォローを解除しました'
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end

  private
  def set_user
    user = User.find(params[:follow_id])
  end

end

app/controllers/site/reports_controller.rb
class Site::ReportsController < Site::Base
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user_id = User.find(params[:user_id]).id
    #respond_to do |format|
      if @report.save
        redirect_to report_path(@report)
        # format.html { render user_report_path(@report.user_id,@report.id), notice: 'Report was successfully created.' }
      else
        redirect_back(fallback_location: root_path)
      end
    #end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :comment, :report_type)
    end
end

app/controllers/site/selections_controller.rb
class Site::SelectionsController < Site::Base
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @selection = Selection.new
  end

  def edit
  end

  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        format.html { redirect_to post_image_path(@selection.post_image_id), notice: 'Selection was successfully created.' }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:post_image_id, :name)
    end
end

app/controllers/site/sessions_controller.rb
class Site::SessionsController < Site::Base
  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/site/users/confirmations_controller.rb
# frozen_string_literal: true

class Site::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/site/users/passwords_controller.rb
# frozen_string_literal: true

class Site::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/site/users/registrations_controller.rb
# frozen_string_literal: true

class Site::Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/site/users/_prof.html.erb
<div class="col-lg-12 col-sm-12">
  <h1>Name:<%= user.name %></h1>
</div>
<div class="col-lg-12 col-sm-3 col-xs-12">
  <div class="circle">
    <% if user.uid.nil? %>
    <%= attachment_image_tag user, :profile_image,　class:"img-circle", fallback: "no_image.jpg", size:'200x200'%>
    <% else %>
    <%= image_tag user.image_origin %>
    <% end %>
  </div>
</div>
<div class="col-lg-12 col-sm-6 col-xs-6 col-lg-offset-0 col-sm-offset-3 col-xs-offset-3">
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to user.name+"が作成したNanikiru", user_created_path(user),class:"btn-flat-simple" %></li>
    <li><%= link_to user.name+"がお気に入りに追加したNanikiru",user_fav_nanikiru_path(user),class:"btn-flat-simple" %></li>
    <li><%= link_to user.name+"がfollowしている", user_following_path(user),class:"btn-flat-simple" %></li>
    <li><%= link_to user.name+"がfollowされている", user_follower_path(user),class:"btn-flat-simple" %></li>
  </ul><br>
</div>
<!-- current-userには通報機能いらない -->
<% if user.id != current_user.id %>
<button type="button" class="btn-flat-bottom-border" data-toggle="collapse" data-target="#report">
  通報
</button>
<div id="report" class="collapse">
  <div class="row report">
    <!-- 通報機能 -->
    <%= form_for [user, report] do |f| %>
    <div class="col-lg-6 col-sm-12 form-inline">
      <label for="">Report type</label>
    </div>
    <div style="padding: 10px%;"></div>
    <%= f.select :report_type, Report.report_types_i18n.keys.map { |k|[Report.report_types_i18n[k], k]},{},{class:"form-control"} %>
    <%= f.text_area :comment,class:"form-control",placeholder: "通報内容を記入してください" %>
    <span>
      <%= f.submit "通報する",data: {confirm: 'このユーザーを通報しますか？' }, class:"btn btn-danger btn-lg btn-block btn-base-1 mt-20" %>
    </span>
    <% end %>
  </div>
</div>
<span class="col-lg-11 col-sm-12">
  <!-- followボタン -->
  <%= render 'site/relationships/follow_button', user: user %>
</span>
<% end %>
<!-- current-user編集 -->
<span class="row">
  <% if user.id == current_user.id %>
  <p>
    <%= link_to "プロフィール編集", edit_user_path(user), class: "btn btn-sm btn-primary"%>
  </p>
  <% end %>
</span>

app/views/site/users/edit.html.erb
<div class="container-fluid">
  <%= form_for(@user) do |f| %>
  <div class="row content">
    <div class="col-lg-3  col-sm-12 sidenav">
      <div class="col-lg-12 col-sm-12">
        <h1><%= @user.name %>編集ページ</h1>
      </div>
      <div class="col-lg-12 col-sm-3">
        <div class="circle">
          <% if @user.uid.nil? %>
          <%= attachment_image_tag @user, :profile_image,　class:"img-circle", fallback: "no_image.jpg", size:'200x200'%>
          <% else %>
          <%= image_tag @user.image_origin %>
          <% end %>
        </div>
        <em> 画像の変更</em>
        <% if @user.uid.nil? %>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        <% else %>
        <p>twitterログインのため画像は変更できません</p>
        <% end %>
      </div>
      <div class="col-lg-12 col-sm-6 col-lg-offset-0 col-sm-offset-3">
        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to @user.name+"が作成したNanikiru", user_created_path(@user) %></li>
          <li><%= link_to @user.name+"がお気に入りに追加したNanikiru",user_fav_nanikiru_path(@user) %></li>
          <li><%= link_to @user.name+"がfollowしている", user_following_path(@user) %></li>
          <li><%= link_to @user.name+"がfollowされている", user_follower_path(@user) %></li>
        </ul><br>
      </div>
      <%= f.submit "変更を保存", class:"btn-primary btn-lg btn-block btn-base-1 mt-20" %>
    </div>

    <div class="col-lg-9 col-sm-12">
      <div class="row">
        <h4><small><%= @user.name %>の編集ページ</small></h4>
        <hr>
        <h2 class="col-lg-12"><%= f.text_field :name %></h2>
        <br>
        <h5>
          <span class="glyphicon glyphicon-time"></span>
          <% if @user.post_images.present?  %>
          最後の何切る投稿日:<%= @user.post_images.last.created_at.time.strftime("%Y年%-m月%-d日 %T") %>
          <% end %>
        </h5>
        <h4><small>自己紹介</small></h4>
        <hr>
        <h2>Introduction</h2>
        <p>
          <h3>自己紹介文を入力してください<%= f.text_field :introduction %></h3>
        </p>
        <div class="col-lg-3 col-sm-12">
          <%= f.submit "変更を保存", class:"btn-primary btn-lg btn-block btn-base-1 mt-20" %>
        </div>
        <br><br><br><br>


        <h4><small>現在の天鳳段位</small></h4>
        <hr>
        <h2>Current ability</h2>
        <div class="col-lg-6 col-sm-12">
          <div class="row">
            <h2>現在の４人麻雀実力[天鳳相当]</h2>
            <h3 class="mark">
              <p>
                <%= f.select :dan_4p_proper, User.dan_4p_propers_i18n.keys.map { |k| [User.dan_4p_propers_i18n[k], k]} %>
              </p>
            </h3>
          </div>
        </div>
        <div class="col-lg-6 col-sm-12">
          <div class="row">
            <h2>現在の３人麻雀実力[天鳳相当]</h2>
            <h3 class="mark">
              <p>
                <%= f.select :dan_3p_proper, User.dan_3p_propers_i18n.keys.map { |k| [User.dan_3p_propers_i18n[k], k]} %>
              </p>
            </h3>
          </div>
        </div>
        <br><br>
        <% end %>
        <h4><small>Game record</small></h4>
        <hr>
        <div class="row">
          <div class="col-lg-3">
            <h2>麻雀ゲーム実績</h2>
          </div>
          <div class="col-lg-4 pull-left">
            <%= link_to "麻雀成績を追加する", new_game_record_path, class:"btn-success btn-lg btn-block btn-base-1 mt-20"%></span>
          </div>
        </div>
        <% if @user.game_records.blank? %>
        <h4><em>麻雀ゲーム実績が登録されていません</em></h4>
        <% end %>
        <div class="col-lg-6 col-sm-12">
          <% current_user.game_records.each do|game_record| %>
          _________________________________
          <%= form_for (game_record) do |f| %>
          <div class="row">
            <div class="field">
              <%= f.label :handle_name %>
              <%= f.text_field :handle_name %>
            </div>

            <div class="field">
              <%= f.label :game_type %>
              <%= f.select :game_type, GameRecord.game_types_i18n.keys.map { |k| [GameRecord.game_types_i18n[k], k]} %>
            </div>

            <div class="field">
              <%= f.label :ability %>
              <%= f.select :ability, GameRecord.abilities_i18n.keys.map { |k| [GameRecord.abilities_i18n[k], k]} %>
            </div>

            <div class="field">
              <%= f.label :game_name %>
              <%= f.select :game_name, GameRecord.game_names_i18n.keys.map { |k| [GameRecord.game_names_i18n[k], k]} %>
            </div>

            <div class="col-lg-6 pull-left">
              <%= f.submit "変更を保存", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
              <%= link_to "削除", game_record_path(game_record), method: "delete", data:{ confirm: "本当に削除しますか"}, class:"btn btn-danger btn-block btn-base-1 mt-20" %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/site/users/show.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-lg-3  col-sm-12 col-xs-12 sidenav">
      <%= render 'site/users/prof', user: @user, report: @report %>
    </div>

    <div class="col-lg-9 col-sm-12">
      <div class="row">
        <h4><small><%= @user.name %>の詳細ページ</small></h4>
        <hr>

        <div>
          <font size="6"> ユーザー名：<%= @user.name %></font>
        </div>
        <!-- followボタン -->
        <span class="col-lg-6 col-sm-6">
          <%= render 'site/relationships/follow_button', user: @user %>
        </span>




        <!-- current-user編集 -->
        <span class="row">
          <% if @user.id == current_user.id %>
          <p>
            <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-xs btn-primary"%>
          </p>
          <% end %>
        </span>

        <br>
        <h5>
          <span class="glyphicon glyphicon-time"></span>
          <% if @user.post_images.present?  %>
          最後の何切る投稿日:<%= @user.post_images.last.created_at.time.strftime("%Y年%-m月%-d日 %T") %>
          <% end %>
        </h5>
        <h4><small>自己紹介</small></h4>
        <hr>
        <h2>Introduction</h2>
        <p>
          <h3><%= @user.introduction %></h3>
        </p>
        <br><br>

        <h4><small>現在の天鳳段位</small></h4>
        <hr>
        <h2>Current ability</h2>
        <div class="col-lg-6 col-sm-12">
          <div class="row">
            <h2>現在の４人麻雀実力[天鳳相当]</h2>
            <h3 class="mark"><strong><%= @user.dan_4p_proper_i18n %></strong></h3>
          </div>
        </div>
        <div class="col-lg-6 col-sm-12">
          <div class="row">
            <h2>現在の３人麻雀実力[天鳳相当]</h2>
            <h3 class="mark"><strong><%= @user.dan_3p_proper_i18n %></strong></h3>
          </div>
        </div>
        <br><br>
        <h4><small>Game record</small></h4>
        <hr>
        <% if @user.id == current_user.id  %>
        <div class="row">
          <div class="col-lg-4">
            <h2>麻雀ゲーム実績</h2>
          </div>
          <div class="col-lg-8">
            <div class="col-lg-4 pull-left">
              <%= link_to "麻雀成績を追加する", new_game_record_path, class:"btn-success btn-lg btn-block btn-base-1 mt-20"%>
              </span>
            </div>
          </div>
        </div>
        <% end %>

        <% if @user.game_records.blank? %>
        <h4><em>麻雀ゲーム実績が登録されていません</em></h4>
        <% end %>
        <div class="col-sm-12">
          <p>
            <% @user.game_records.each do|game_record| %>
            <div class="row" style="margin: 0px;">
              _________________________________
              <div class="row">
                <label>Mahjong game type:</label>
                <%= game_record.game_type_i18n %>
              </div>
              <div class="row">
                <label>Game:</label>
                <%= game_record.game_name_i18n %>
              </div>
              <div class="row">
                <label>Handle name for game :</label>
                <%= game_record.handle_name %>
              </div>
              <div class="row">
                <label>Game strength: </label>
                <%= game_record.ability_i18n %>
              </div>
            </div>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>