config/routes.rb
Rails.application.routes.draw do
  # namespace :manager do
  #     devise_for :admin_users, controllers: {
  #     sessions: 'manager/admin_users/sessions',
  #     registrations: 'manager/admin_users/registrations',
  #     passwords: 'manager/admin_users/passwords'
  #   }
  # end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  scope module: 'site' do
    resources :post_images do
      resources :answers, only: [:create, :show]
      get 'like', to: 'favorites#like'
      get 'unlike', to: 'favorites#unlike'
    end
    resources :game_records, only: [:new, :create, :update, :destroy]
    resources :selections
    resources :answers
    resources :post_comments
    resources :reports, only: [:show]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      resources :reports, only: [:create]
      get 'created', to: 'post_images#created'
      get 'selected', to: 'post_images#selected'
      get 'fav_nanikiru', to: 'favorites#nanikiru'
      get 'following', to: 'users#following_index'
      get 'follower', to: 'users#follower_index'
      get 'follow_nanikiru', to: 'users#follow_nanikiru'
    end
    resources :relationships, only: [:create, :destroy]
    root to: 'users#welcome'
    get 'nanikiru_all', to: 'post_images#index_all'
    get 'nanikiru_4p', to: 'post_images#index_4p'
    get 'nanikiru_3p', to: 'post_images#index_3p'
    get 'nanikiru_other', to: 'post_images#index_other'
  end
end

app/views/shared_site/_header_sign_out.html.erb
<nav class="navbar navbar-inverse nav-sticky">
	<div class="nav_rp">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Nanikiru?", post_images_path ,class:"navbar-brand" %>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<!-- sign_up -->
				<li>
					<%= link_to new_user_registration_path do %>
					<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
					新規登録
					<% end %>
				</li>
				<!-- sign_in -->
				<li>
					<%= link_to new_user_session_path do %>
					<span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
					ログイン
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>

app/views/shared_site/_header_signed_in.html.erb
<nav class="navbar navbar-inverse nav-sticky">
	<div class="nav_rp">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Nanikiru?", post_images_path ,class:"navbar-brand" %>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to new_post_image_path do%>
					<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
					新規投稿
					<% end %>
				</li>
				<!-- nanikiru一覧 -->
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<span class="glyphicon glyphicon-th" aria-hidden="true"></<span>
							Nanikiru
							<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "新着順", nanikiru_all_path %>
						</li>
						<li>
							<%= link_to "4人麻雀", nanikiru_4p_path %>
						</li>
						<li>
							<%= link_to  "3人麻雀", nanikiru_3p_path %>
						</li>
						<li>
							<%= link_to  "その他", nanikiru_other_path %>
						</li>
					</ul>
				</li>
				<!-- お気に入り -->
				<li>
					<%= link_to user_fav_nanikiru_path(current_user) do%>
					<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
					お気に入り
					<% end %>
				</li>
				<!-- フォロー -->
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
						follow
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to  current_user.name+"がフォローしている", user_following_path(current_user) %>
						</li>
						<li>
							<%= link_to  current_user.name+"がフォローされている", user_follower_path(current_user) %>
						</li>
						<li>
							<%= link_to  current_user.name+"がフォローしているユーザーのNanikiru", user_follow_nanikiru_path(current_user) %>
						</li>
					</ul>
				</li>
				<!-- userページ -->
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
						<%= current_user.name %>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "ユーザー情報詳細ページ", user_path(current_user.id) %>
						</li>
						<li>
							<%= link_to "ユーザー情報編集ページ", edit_user_path(current_user.id) %>
						</li>
						<li>
							<%= link_to  current_user.name+"が作成したNanikiru", user_created_path(current_user) %>
						</li>
						<li>
							<%= link_to  current_user.name+"が回答したNanikiru", user_selected_path(current_user) %>
						</li>
					</ul>
				</li>
				<!-- 一覧 -->
				<li class="dropdown ">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
							<%= link_to "ユーザー一覧", users_path %>
						</li>
						<li>
							<%= link_to "Nanikiru一覧", post_images_path %>
						</li>
					</ul>
				</li>
				<!-- logout -->
				<li>
					<%= link_to destroy_user_session_path, method: :delete do %>
					<span class="glyphicon glyphicon-log-in"></span>
					Loout
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</nav>