config/routes.rb
Rails.application.routes.draw do
  # namespace :manager do
  #     devise_for :admin_users, controllers: {
  #     sessions: 'manager/admin_users/sessions',
  #     registrations: 'manager/admin_users/registrations',
  #     passwords: 'manager/admin_users/passwords'
  #   }
  # end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  scope module: 'site' do
    resources :post_images do
      resources :answers, only: [:create, :show]
      get 'like', to: 'favorites#like'
      get 'unlike', to: 'favorites#unlike'
    end
    resources :game_records, only: [:new, :create, :update, :destroy]
    resources :selections
    resources :answers
    resources :post_comments
    resources :reports, only: [:show]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      resources :reports, only: [:create]
      get 'created', to: 'post_images#created'
      get 'selected', to: 'post_images#selected'
      get 'fav_nanikiru', to: 'favorites#nanikiru'
      get 'following', to: 'users#following_index'
      get 'follower', to: 'users#follower_index'
      get 'follow_nanikiru', to: 'users#follow_nanikiru'
    end
    resources :relationships, only: [:create, :destroy]
    root to: 'users#welcome'
    get 'nanikiru_all', to: 'post_images#index_all'
    get 'nanikiru_4p', to: 'post_images#index_4p'
    get 'nanikiru_3p', to: 'post_images#index_3p'
    get 'nanikiru_other', to: 'post_images#index_other'
  end
end

app/models/site.rb
module Site
  def self.table_name_prefix
    'site_'
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]

  # GET /post_images
  # GET /post_images.json
  def index
    @post_images = PostImage.all
  end

  # GET /post_images/1
  # GET /post_images/1.json
  def show
  end

  # GET /post_images/new
  def new
    @post_image = PostImage.new
  end

  # GET /post_images/1/edit
  def edit
  end

  # POST /post_images
  # POST /post_images.json
  def create
    @post_image = PostImage.new(post_image_params)

    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        format.json { render :show, status: :created, location: @post_image }
      else
        format.html { render :new }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_images/1
  # PATCH/PUT /post_images/1.json
  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_images/1
  # DELETE /post_images/1.json
  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url, notice: 'Post image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_image_params
      params.require(:post_image).permit(:user_id, :type, :image_id, :comment)
    end
end

app/controllers/site/answers_controller.rb
class Site::AnswersController < Site::Base
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = Answer.all
  end



  def show
    @answer = Answer.find(params[:id])
    @post_image = PostImage.find(params[:post_image_id])
    @post_comment = PostComment.new
    @selections = @post_image.selections
    # post_imagesに対するcommentsをidが古い順に抽出
    comments = @answer.post_image_comments(@post_image)
    @comments = Kaminari.paginate_array(comments).page(params[:page]).per(50)
  end

  def new
  end

  def edit
  end

  def create
     @post_image = PostImage.find(params[:post_image_id])
     # 重複した選択肢を削除する
     current_user.same_answer_destroy
    # 回答済みのNanikiruかどうか
    if @post_image.answered?(current_user)
      # 回答済みのユーザーは回答出来ずに結果画面にリダイレクトする
        if answered_id = @post_image.answered_id(current_user)
          flash[:danger] = '回答済みのNanikiruです！！'
          redirect_to post_image_answer_path(@post_image.id,answered_id)
        else
          flash[:danger] = '[Error!]回答に問題があります'
          redirect_to root_path
        end
      else
      # 回答済みのではない場合save
      @answer = Answer.new(answer_params)
      @answer.user_id = current_user.id
      respond_to do |format|
        if @answer.save
          format.html { redirect_to post_image_answer_path(params[:post_image_id],@answer.id), notice: 'Answer was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :selection_id)
    end
end

app/controllers/site/base.rb
class Site::Base < ApplicationController
	layout 'site'
end

app/controllers/site/favorites_controller.rb
class Site::FavoritesController < Site::Base
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  def nanikiru
   @user = User.find(params[:user_id])
   @favorites = @user.favorites
  end


  def create
    redirect_back(fallback_location:root_path)
  end

  def destroy
    @favorite.destroy
    # respond_to do |format|
    #   format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
    # end
  end

  def like
    @post_image = PostImage.find(params[:post_image_id])
    current_user.like(@post_image)
    redirect_back(fallback_location:root_path)
  end

  def unlike
    @post_image = PostImage.find(params[:post_image_id])
    current_user.unlike(@post_image)
    redirect_back(fallback_location:root_path)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :post_image_id)
    end
end

app/controllers/site/game_records_controller.rb
class Site::GameRecordsController < Site::Base
  before_action :set_game_record, only: [:show, :edit, :update, :destroy]
  def new
    @game_record = GameRecord.new
  end

  def edit
  end

  def create
    @game_record = GameRecord.new(game_record_params)
    @game_record.user_id = current_user.id
    respond_to do |format|
      if @game_record.save
        format.html { redirect_to user_path(current_user), notice: 'Game record was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @game_record.update(game_record_params)
        format.html { redirect_to user_path(current_user), notice: 'Game record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @game_record.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@game_record.user_id), notice: 'Game record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_record
      @game_record = GameRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_record_params
      params.require(:game_record).permit(:user_id, :handle_name, :game_type, :ability, :game_name)
    end
end

app/controllers/site/homes_controller.rb
class Site::HomesController < Site::Base
  def index
    if session[:user_id].nil?
      redirect_to action:'login'
    else
      @user = User.find(session[:user_id])
    end
  end

  def login
  end
end

app/controllers/site/post_comments_controller.rb
class Site::PostCommentsController < Site::Base
  def create
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.answer_id = params[:answer_id]
    respond_to do |format|
      if @post_comment.save
        format.html { redirect_to post_image_answer_path(@post_comment.answer.selection.post_image_id,@post_comment.answer_id), notice: 'Answer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def destroy
  end
  def new
  end
  private
  def post_comment_params
    params.require(:post_comment).permit(:ansewr_id, :comment)
  end
end

app/controllers/site/post_images_controller.rb
class Site::PostImagesController < Site::Base
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]
  def index
    @post_images = PostImage.page(params[:page]).reverse_order.per(9)
    @post_4p_images = PostImage.where(image_type: "player_4").page(params[:page]).reverse_order.per(9)
    @post_3p_images = PostImage.where(image_type: "player_3").page(params[:page]).reverse_order.per(9)
    @post_other_images = PostImage.where(image_type: "others").page(params[:page]).reverse_order.per(9)
  end

  def index_all
    @post_images = PostImage.page(params[:page]).reverse_order.per(12)
  end

  def index_4p
    @post_4p_images = PostImage.where(image_type: "player_4").page(params[:page]).reverse_order.per(12)
  end

  def index_3p
    @post_3p_images = PostImage.where(image_type: "player_3").page(params[:page]).reverse_order.per(12)
  end

  def index_other
    @post_other_images = PostImage.where(image_type: "others").page(params[:page]).reverse_order.per(12)
  end

  def show
    # 重複した選択肢を削除する
    current_user.same_answer_destroy
    @post_image = PostImage.find(params[:id])
    # selectの削除
    @post_image.selections.where(name: "select").destroy_all
    # 回答済みのユーザーを回答済み画面にリダイレクト
    if @post_image.answered?(current_user)
      answered_id = @post_image.answered_id(current_user)
      if answered_id
        redirect_to post_image_answer_path(@post_image.id,answered_id)
      else
        flash[:danger] = '[Error!]回答が存在しません'
        redirect_to root_path
      end
    end
    @selection = Selection.new
    @answer = Answer.new
    @report = Report.new
  end

  def new
    @post_image = PostImage.new
    @post_image.selections.build
  end

  def edit
    @report = Report.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        else
        format.html { render :new }
      end
    end
    # 選択肢の重複の削除
    @post_image.same_selection_destroy
  end
  # user_created_nanikiruページ
  def created
    @user = User.find(params[:user_id])
    @post_images = @user.post_images
    @report = Report.new
  end
  # user_selected_nanikiru
  def selected
    @user = User.find(params[:user_id])
    @answers = @user.answers
    # 重複した選択肢を削除する
    @user.same_answer_destroy
  end

  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url, notice: 'Post image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    def post_image_params
      params.require(:post_image).permit(:user_id, :image_type, :image, :comment, selections_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/site/relationships_controller.rb
class Site::RelationshipsController < Site::Base
before_action :set_user

  def create
    user = User.find(params[:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:info] = 'ユーザーをフォローしました'
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:info] = 'ユーザーのフォローを解除しました'
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end

  private
  def set_user
    user = User.find(params[:follow_id])
  end

end

app/controllers/site/reports_controller.rb
class Site::ReportsController < Site::Base
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user_id = User.find(params[:user_id]).id
    #respond_to do |format|
      if @report.save
        redirect_to report_path(@report)
        # format.html { render user_report_path(@report.user_id,@report.id), notice: 'Report was successfully created.' }
      else
        redirect_back(fallback_location: root_path)
      end
    #end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :comment, :report_type)
    end
end

app/controllers/site/selections_controller.rb
class Site::SelectionsController < Site::Base
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @selection = Selection.new
  end

  def edit
  end

  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        format.html { redirect_to post_image_path(@selection.post_image_id), notice: 'Selection was successfully created.' }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:post_image_id, :name)
    end
end

app/controllers/site/sessions_controller.rb
class Site::SessionsController < Site::Base
  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/site/users/confirmations_controller.rb
# frozen_string_literal: true

class Site::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/views/site/post_images/_card.html.erb
<div class="card" style="margin-bottom: 10px;">
  <!-- Nanikiru画像 -->
  <div>
    <%= link_to post_image_path(post_image.id), :style=>"display: inline-block; cursor: pointer; width:100%;" do  %>
    <%= attachment_image_tag post_image, :image,:fill, 800, 800,class: "pull-left img-responsive", fallback: "no_image.jpg", size:'600x600'%>
    <% end %>
  </div>
  <!-- プロフィール画像 -->
  <div class="row">

    <div class="profile col-xs-3 col-sm-3 col-md-3 col-lg-3">
      <div>
        <%= link_to user_path(post_image.user_id), :style=>"display: inline-block; cursor: pointer;" do %>
        <% if post_image.user.uid.nil? %>
        <%= attachment_image_tag post_image.user, :profile_image,class: "img-circle profile-thumb", fallback: "no_image.jpg", size:'200x200' %>
        <% else %>
        <%= image_tag post_image.user.image_origin %>
        <% end %>
        <br>
        <%end%>
      </div>
    </div>

    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
      <h4 class="text-right">
        <%= link_to user_path(post_image.user_id), :style=>"display: inline-block; cursor: pointer;" do %>
        <%= post_image.user.name_cut %>
        <%end%>
      </h4>
    </div>
    <!-- コメント有無で条件分岐 -->
    <span style="margin: 20px; opacity: 0.65;">
      <% if post_image.comment.present? %>

      <%= post_image.comment_cut %>

      <% else %>

      コメントなし

      <% end %>
    </span>
    <% if user_signed_in? %>
    <span class="favorite" style="padding: 5px 0px 10px 5px">
      <!-- ==render favorite== -->
      <%= render 'site/favorites/favorite', post_image: post_image %>
    </span>
    <% else %>
    <%=  link_to new_user_session_path do %>
    <i class="far fa-heart fa-2x" aria-hidden="true" style="color: red;"></i>
    <span class="text-fav"><%= post_image.favorites.count %> いいね</span>
    <% end %>
    <% end %>
  </div>
</div>

app/views/site/post_images/_form.html.erb
<%= form_with model: @post_image,local: true do |form| %>

<label for="">Name</label>
<%= current_user.name %>

<div class="field">
  <label for="">Game type</label>
  <%= form.select :image_type, PostImage.image_types_i18n.keys.map { |k| [PostImage.image_types_i18n[k], k]} %>
</div>

<div class="field">
  <label for="">画像投稿</label>
  <div>
    <%= attachment_image_tag @post_image, :image, :fill, 200, 200, class: "pull-left profile-thumb", fallback: "no_image.jpg"%>
    <%= form.attachment_field :image %>
  </div>
</div>

<!-- cocoonによる選択肢追加 -->
<div class="selections">
  <%= form.fields_for :selections do |f| %>
  <%= render "selection_fields", f: f %>
  <% end %>
  <div class="links">
    <%= link_to_add_association "選択肢追加", form, :selections %>
  </div>
</div>

<div class="field">
  <%= form.label :comment %>
  <%= form.text_area :comment %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/site/post_images/_selection_fields.html.erb
<div class="nested-fields">
  <%= f.select :name, Selection.names_i18n.keys.map { |k| [Selection.names_i18n[k], k]} %>
  <%= link_to_remove_association "削除", f,class:"btn btn-danger" %>
</div>

app/views/site/post_images/_style.html.erb
 <div class="index-content">
   <div class="container-fluid">
     <% post_images.each do |post_image| %>
     <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
       <!-- card -->
       <%= render 'site/post_images/card', post_image: post_image %>
     </div>
     <% end %>
   </div>
 </div>

app/views/site/post_images/created.html.erb
 <div class="container-fluid">
   <div class="row content content-back">
     <!-- 左側 -->
     <div class="col-lg-3  col-sm-12 sidenav">
       <%= render 'site/users/prof', user: @user, report: @report %>
     </div>
     <!-- 右側 -->
     <div class="col-lg-9 col-sm-12">
       <div class="container-fluid padding-none">
         <%= render 'site/post_images/style', post_images: @post_images %>
       </div>
     </div>
   </div>
 </div>

app/views/site/post_images/index.html.erb
<!-- タブ・メニュー -->
<div class="nav-back sticky">
  <ul class="nav nav-tabs center">
    <li class="active"><a href="#index" data-toggle="tab">新着順</a></li>
    <li><a href="#index-4p" data-toggle="tab">4人麻雀</a></li>
    <li><a href="#index-3p" data-toggle="tab">3人麻雀</a></li>
    <li><a href="#index-others" data-toggle="tab">その他</a></li>
  </ul>
</div>
<div class="container-fluid top-fluid">
  <!-- タブ内容 -->
  <div class="tab-content">
    <!-- 新着順全て -->
    <div class="tab-pane fade in active" id="index">
      <%= render 'site/post_images/style', post_images: @post_images %>
    </div>
    <!-- 4人麻雀 -->
    <div class="tab-pane fade in" id="index-4p">
      <%= render 'site/post_images/style', post_images: @post_4p_images %>
    </div>
    <!-- 3人麻雀 -->
    <div class="tab-pane fade in" id="index-3p">
      <%= render 'site/post_images/style', post_images: @post_3p_images %>
    </div>
    <!-- その他 -->
    <div class="tab-pane fade in" id="index-others">
      <%= render 'site/post_images/style', post_images: @post_other_images %>
    </div>
  </div>

  <!-- footer -->
  <div class="fixed">
    <div class="row">
      <div class="col-lg-3 col-sm-6">
        <span>
          <%= link_to nanikiru_all_path do%>
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
          新着順
          <% end %>
        </span>
      </div>
      <div class="col-lg-3 col-sm-6">
        <span>
          <%= link_to nanikiru_4p_path do %>
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
          4人麻雀
          <% end %>
        </span>
      </div>
      <div class="col-lg-3 col-sm-6">
        <span>
          <%= link_to nanikiru_3p_path do %>
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
          3人麻雀
          <% end %>
        </span>
      </div>
      <div class="col-lg-3 col-sm-6">
        <span>
          <%= link_to nanikiru_other_path do %>
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
          その他
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/site/post_images/index_4p.html.erb
<div class="container-fluid">
  <%= render 'site/post_images/style', post_images: @post_4p_images %>
  <div class="fixed">
    <%= paginate @post_4p_images, class: "paginate" %>
  </div>
</div>

app/views/site/post_images/index_all.html.erb
<div class="container-fluid">
  <%= render 'site/post_images/style', post_images: @post_images %>
  <div class="fixed">
    <%= paginate @post_images, class: "paginate" %>
  </div>
</div>

app/views/site/post_images/show.html.erb
      <div class="container-fluid">
        <div class="row content content-back">
          <!-- 左側 -->
          <div class="col-lg-3  col-sm-12 sidenav">
            <%= render 'site/users/prof', user: @post_image.user, report: @report %>
          </div>
          <!-- 右側 -->
          <div class="col-lg-9 col-sm-12">
            <div class="row">
              <div class="index-content mg-none">
                <div class="col-xs-12 col-sm-12 col-lg-6 col-lg-offset-2" style="padding-top: 20px;">
                  <!-- render_card -->
                  <%= render 'site/post_images/card', post_image: @post_image %>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  <h3>コメント</h3>
                  <p><%= @post_image.comment %></p>
                </div>
                <div class="col-lg-12">
                  <h3><small>あなたは何切る？？</small></h3>
                  <h4><small>クリックするとアンケート結果画面に飛びます！！</small></h4>
                </div>
                <div class="col-lg-12 mt-10">
                  <!-- 選択肢一覧 -->
                  <!-- selectionsの重複を表示させない -->
                  <div class="col-sm-12">
                    <div class="select-back">
                      <% selection_name_array = [] %>
                      <% if @post_image.selections.blank? %>
                      <h5><label for="select">選択肢がありません!!新しく選択肢を追加して下さい</label>
                      </h5>
                      <% end %>
                      <% @post_image.selections.each do |selection| %>
                      <!-- 選択肢に初期設定のselectを表示させないかつ選択肢が重複していない -->
                      <% if selection.name != "select" && selection_name_array.exclude?(selection.name) %>
                      <% selection_name_array.push(selection.name) %>
                      <%= form_for [@post_image, @answer] do |f| %>
                      <%= f.hidden_field :selection_id, :value => selection.id %>
                      <%= f.submit selection.name_i18n, class: "btn btn-lg btn-success active" %>
                      <% end %>
                      <% end %>
                      <% end %>
                    </div>
                  </div>
                  <%= form_with model: @selection, local: true do |form| %>
                  <%= form.hidden_field :post_image_id, :value => @post_image.id %>
                  <div class="col-lg-7 col-sm-12">
                    <%= form.select :name, Selection.names_i18n.keys.map { |k| [Selection.names_i18n[k], k]},{},{class:"form-control"} %>
                  </div>
                  <div class="col-lg-5 col-sm-12">
                    <%= form.submit "新しい選択肢を追加する",class:"btn-sm btn-info",style:"margin-bottom:30px" %>
                  </div>
                  <% end %>
                  <br><br><br><br><br><br>
                  <% if @post_image.user_id == current_user.id %>
                  <%= link_to 'Edit', edit_post_image_path(@post_image),class:"btn edit-btn btn-block" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/site/post_images/test_image.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post_image.user.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @post_image.image_type_i18n %>
</p>

<p>
  <%= attachment_image_tag @post_image, :image, :fill, 300, 300, class: "pull-left profile-thumb", fallback: "no_image.jpg"%>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post_image.comment %>
</p>

<div>
  <!-- 選択肢一覧 -->
  <!-- selectionsの重複を表示させない -->
  <% selection_name_array = [] %>
  <% @post_image.selections.each do |selection| %>
  <!-- 選択肢に初期設定のselectを表示させないかつ選択肢が重複していない -->
  <% if selection.name != "select" && selection_name_array.exclude?(selection.name) %>
  <% selection_name_array.push(selection.name) %>
  <%= form_for [@post_image, @answer] do |f| %>
  <div>
    <%= f.hidden_field :selection_id, :value => selection.id %>
    <%= f.submit selection.name_i18n, class: "btn btn-sm btn-primary" %>
  </div>
  <% end %>
  <% end %>
  <% end %>
</div>
<%= form_with model: @selection, local: true do |form| %>
<%= form.hidden_field :post_image_id, :value => @post_image.id %>
<%= form.select :name, Selection.names_i18n.keys.map { |k| [Selection.names_i18n[k], k]} %>
<%= form.submit "新しい選択肢を追加する",class:"btn-sm btn-primary" %>
<% end %>
</div>
<% if @post_image.user_id == current_user.id %>
<%= link_to 'Edit', edit_post_image_path(@post_image) %> |
<% end %>
<%= link_to 'Back', post_images_path %>