config/routes.rb
Rails.application.routes.draw do
  # namespace :manager do
  #     devise_for :admin_users, controllers: {
  #     sessions: 'manager/admin_users/sessions',
  #     registrations: 'manager/admin_users/registrations',
  #     passwords: 'manager/admin_users/passwords'
  #   }
  # end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  scope module: 'site' do
    resources :post_images do
      resources :answers, only: [:create, :show]
      get 'like', to: 'favorites#like'
      get 'unlike', to: 'favorites#unlike'
    end
    resources :game_records, only: [:new, :create, :update, :destroy]
    resources :selections
    resources :answers
    resources :post_comments
    resources :reports, only: [:show]
    resources :users, only: [:show, :edit, :update, :index, :destroy] do
      resources :reports, only: [:create]
      get 'created', to: 'post_images#created'
      get 'selected', to: 'post_images#selected'
      get 'fav_nanikiru', to: 'favorites#nanikiru'
      get 'following', to: 'users#following_index'
      get 'follower', to: 'users#follower_index'
      get 'follow_nanikiru', to: 'users#follow_nanikiru'
    end
    resources :relationships, only: [:create, :destroy]
    root to: 'users#welcome'
    get 'nanikiru_all', to: 'post_images#index_all'
    get 'nanikiru_4p', to: 'post_images#index_4p'
    get 'nanikiru_3p', to: 'post_images#index_3p'
    get 'nanikiru_other', to: 'post_images#index_other'
  end
end

app/models/site.rb
module Site
  def self.table_name_prefix
    'site_'
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :selection_id, :comment)
    end
end

app/controllers/site/answers_controller.rb
class Site::AnswersController < Site::Base
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = Answer.all
  end



  def show
    @answer = Answer.find(params[:id])
    @post_image = PostImage.find(params[:post_image_id])
    @post_comment = PostComment.new
    @selections = @post_image.selections
    # post_imagesに対するcommentsをidが古い順に抽出
    comments = @answer.post_image_comments(@post_image)
    @comments = Kaminari.paginate_array(comments).page(params[:page]).per(50)
  end

  def new
  end

  def edit
  end

  def create
     @post_image = PostImage.find(params[:post_image_id])
     # 重複した選択肢を削除する
     current_user.same_answer_destroy
    # 回答済みのNanikiruかどうか
    if @post_image.answered?(current_user)
      # 回答済みのユーザーは回答出来ずに結果画面にリダイレクトする
        if answered_id = @post_image.answered_id(current_user)
          flash[:danger] = '回答済みのNanikiruです！！'
          redirect_to post_image_answer_path(@post_image.id,answered_id)
        else
          flash[:danger] = '[Error!]回答に問題があります'
          redirect_to root_path
        end
      else
      # 回答済みのではない場合save
      @answer = Answer.new(answer_params)
      @answer.user_id = current_user.id
      respond_to do |format|
        if @answer.save
          format.html { redirect_to post_image_answer_path(params[:post_image_id],@answer.id), notice: 'Answer was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :selection_id)
    end
end

app/controllers/site/base.rb
class Site::Base < ApplicationController
	layout 'site'
end

app/controllers/site/favorites_controller.rb
class Site::FavoritesController < Site::Base
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  def nanikiru
   @user = User.find(params[:user_id])
   @favorites = @user.favorites
  end


  def create
    redirect_back(fallback_location:root_path)
  end

  def destroy
    @favorite.destroy
    # respond_to do |format|
    #   format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
    # end
  end

  def like
    @post_image = PostImage.find(params[:post_image_id])
    current_user.like(@post_image)
    redirect_back(fallback_location:root_path)
  end

  def unlike
    @post_image = PostImage.find(params[:post_image_id])
    current_user.unlike(@post_image)
    redirect_back(fallback_location:root_path)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :post_image_id)
    end
end

app/controllers/site/game_records_controller.rb
class Site::GameRecordsController < Site::Base
  before_action :set_game_record, only: [:show, :edit, :update, :destroy]
  def new
    @game_record = GameRecord.new
  end

  def edit
  end

  def create
    @game_record = GameRecord.new(game_record_params)
    @game_record.user_id = current_user.id
    respond_to do |format|
      if @game_record.save
        format.html { redirect_to user_path(current_user), notice: 'Game record was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @game_record.update(game_record_params)
        format.html { redirect_to user_path(current_user), notice: 'Game record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @game_record.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@game_record.user_id), notice: 'Game record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_record
      @game_record = GameRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_record_params
      params.require(:game_record).permit(:user_id, :handle_name, :game_type, :ability, :game_name)
    end
end

app/controllers/site/homes_controller.rb
class Site::HomesController < Site::Base
  def index
    if session[:user_id].nil?
      redirect_to action:'login'
    else
      @user = User.find(session[:user_id])
    end
  end

  def login
  end
end

app/controllers/site/post_comments_controller.rb
class Site::PostCommentsController < Site::Base
  def create
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.answer_id = params[:answer_id]
    respond_to do |format|
      if @post_comment.save
        format.html { redirect_to post_image_answer_path(@post_comment.answer.selection.post_image_id,@post_comment.answer_id), notice: 'Answer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def destroy
  end
  def new
  end
  private
  def post_comment_params
    params.require(:post_comment).permit(:ansewr_id, :comment)
  end
end

app/controllers/site/post_images_controller.rb
class Site::PostImagesController < Site::Base
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_post_image, only: [:show, :edit, :update, :destroy]
  def index
    @post_images = PostImage.page(params[:page]).reverse_order.per(9)
    @post_4p_images = PostImage.where(image_type: "player_4").page(params[:page]).reverse_order.per(9)
    @post_3p_images = PostImage.where(image_type: "player_3").page(params[:page]).reverse_order.per(9)
    @post_other_images = PostImage.where(image_type: "others").page(params[:page]).reverse_order.per(9)
  end

  def index_all
    @post_images = PostImage.page(params[:page]).reverse_order.per(12)
  end

  def index_4p
    @post_4p_images = PostImage.where(image_type: "player_4").page(params[:page]).reverse_order.per(12)
  end

  def index_3p
    @post_3p_images = PostImage.where(image_type: "player_3").page(params[:page]).reverse_order.per(12)
  end

  def index_other
    @post_other_images = PostImage.where(image_type: "others").page(params[:page]).reverse_order.per(12)
  end

  def show
    # 重複した選択肢を削除する
    current_user.same_answer_destroy
    @post_image = PostImage.find(params[:id])
    # selectの削除
    @post_image.selections.where(name: "select").destroy_all
    # 回答済みのユーザーを回答済み画面にリダイレクト
    if @post_image.answered?(current_user)
      answered_id = @post_image.answered_id(current_user)
      if answered_id
        redirect_to post_image_answer_path(@post_image.id,answered_id)
      else
        flash[:danger] = '[Error!]回答が存在しません'
        redirect_to root_path
      end
    end
    @selection = Selection.new
    @answer = Answer.new
    @report = Report.new
  end

  def new
    @post_image = PostImage.new
    @post_image.selections.build
  end

  def edit
    @report = Report.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    respond_to do |format|
      if @post_image.save
        format.html { redirect_to @post_image, notice: 'Post image was successfully created.' }
        else
        format.html { render :new }
      end
    end
    # 選択肢の重複の削除
    @post_image.same_selection_destroy
  end
  # user_created_nanikiruページ
  def created
    @user = User.find(params[:user_id])
    @post_images = @user.post_images
    @report = Report.new
  end
  # user_selected_nanikiru
  def selected
    @user = User.find(params[:user_id])
    @answers = @user.answers
    # 重複した選択肢を削除する
    @user.same_answer_destroy
  end

  def update
    respond_to do |format|
      if @post_image.update(post_image_params)
        format.html { redirect_to @post_image, notice: 'Post image was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_image }
      else
        format.html { render :edit }
        format.json { render json: @post_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post_image.destroy
    respond_to do |format|
      format.html { redirect_to post_images_url, notice: 'Post image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post_image
      @post_image = PostImage.find(params[:id])
    end

    def post_image_params
      params.require(:post_image).permit(:user_id, :image_type, :image, :comment, selections_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/site/relationships_controller.rb
class Site::RelationshipsController < Site::Base
before_action :set_user

  def create
    user = User.find(params[:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:info] = 'ユーザーをフォローしました'
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:info] = 'ユーザーのフォローを解除しました'
      redirect_to user
    else
      flash.now[:danger] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end

  private
  def set_user
    user = User.find(params[:follow_id])
  end

end

app/controllers/site/reports_controller.rb
class Site::ReportsController < Site::Base
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user_id = User.find(params[:user_id]).id
    #respond_to do |format|
      if @report.save
        redirect_to report_path(@report)
        # format.html { render user_report_path(@report.user_id,@report.id), notice: 'Report was successfully created.' }
      else
        redirect_back(fallback_location: root_path)
      end
    #end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:user_id, :comment, :report_type)
    end
end

app/controllers/site/selections_controller.rb
class Site::SelectionsController < Site::Base
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @selection = Selection.new
  end

  def edit
  end

  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        format.html { redirect_to post_image_path(@selection.post_image_id), notice: 'Selection was successfully created.' }
        format.json { render :show, status: :created, location: @selection }
      else
        format.html { render :new }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url, notice: 'Selection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:post_image_id, :name)
    end
end

app/controllers/site/sessions_controller.rb
class Site::SessionsController < Site::Base
  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/site/users/confirmations_controller.rb
# frozen_string_literal: true

class Site::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/views/site/answers/_favorite.html.erb
<% if current_user.favorited_by?(@post_image) %>
<%= link_to post_image_unlike_path do %>
<i class="fas fa-heart fa-2x" aria-hidden="true" style="color: red;"></i>
<span class="text-fav"><%= @post_image.favorites.count %> いいね</span>
<% end %>
<% else %>
<%=  link_to post_image_like_path do %>
<i class="far fa-heart fa-2x" aria-hidden="true" style="color: red;"></i>
<span class="text-fav"><%= @post_image.favorites.count %> いいね</span>
<% end %>
<% end %>

app/views/site/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :selection_id %>
    <%= form.number_field :selection_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/site/answers/_modal.html.erb
<!-- モーダル -->
<div class="modal fade" id=<%= selection.name %> tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">回答者情報:<%= selection.name_i18n %></h4>
      </div>
      <div class="modal-body">
        <table class="table table-stripe">
          <tbody>
            <tr>
              <th class="info">ユーザー名</th>
              <th class="warning">４人麻雀段位</th>
              <th class="warning">３人麻雀段位</th>
            </tr>
            <% selection.answers.each do |answer| %>
            <tr>
              <td><%= answer.user.name %></td>
              <td><%= answer.user.dan_4p_proper_i18n %></td>
              <td><%= answer.user.dan_3p_proper_i18n %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/site/answers/show.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- 左側 -->
    <div class="col-lg-6 margin-col col-xs-12 col-sm-12">
      <div class="row">
        <div class="index-content back-none">
          <div class="col-xs-12 col-sm-12 col-lg-12">
            <!-- render_card -->
            <%= render 'site/post_images/card', post_image: @post_image %>
          </div>
        </div>
      </div>
      <div class="row">
        <h3>　コメント</h3>
        <p>　<%= @post_image.comment %></p>
      </div>
      <div class="row">
        <!-- editボタン -->
        <% if @post_image.user_id == current_user.id %>
        <%= link_to 'Edit', edit_post_image_path(@post_image.id),class:"btn btn-info btn-block edit-btn" %>
        <% end %>
      </div>
    </div>
    <!-- 右側 -->
    <div class="col-lg-6 col-sm-12">
      <div class="row">
        <div class="col-lg-12">
          <div class="charts">
            <div class="chart chart--dev">
              <span class="chart__title">
                <h2>Answers</h2>
              </span>
              <div class="chart-margin">
                <ul class="chart--horiz">
                  <!-- 重複したselectionを表示しない -->
                  <% selection_name_array = [] %>
                  <% @selections.each do |selection| %>
                  <% if selection.name != "select" && selection_name_array.exclude?(selection.name) %>
                  <% selection_name_array.push(selection.name) %>
                  <!-- 重複したselectionを表示しない -->

                  <!-- answers のパラメータ作成 -->
                  <% answers_count = 0 %>
                  <% @selections.each do |selection| %>
                  <% answers_count += selection.answer_count %>
                  <% end %>
                  <div class="row col-lg-9 col-sm-9 col-xs-9">
                    <li class="chart__bar"
                      style="width: <%= ((selection.answer_count.to_f/answers_count.to_f)*100).to_f.round.to_s %>%; min-width: 2em;">
                      <span class="chart__label">
                        <%= selection.name_i18n %>
                      </span>
                    </li>
                  </div>
                  <div class="row col-lg-3 col-sm-3 col-xs-3 chart-modal">
                    <!-- モーダルボタン -->
                    <button type="button" class="btn btn-primary" data-toggle="modal"
                      data-target=<%= "#"+selection.name %>>
                      回答数: <%= selection.answer_count %>
                    </button>
                    <!-- ==render モーダル内容== -->
                    <%= render :partial => "modal",locals: {selection: selection} %>
                  </div>
                  <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <!-- comment入力 -->
      <div class="well col-lg-12">
        <div>
          <label for="l1">
            <span>
              <h3><em><%= @answer.user.name %> answer</em></h3>
            </span>
            <span class="btn btn-success text-size"><%= @answer.selection.name_i18n %></span>
            <span>**意見を投稿する</span>
          </label>
        </div>
        <div>
          <%= form_for @post_comment, url: post_comments_path do |form| %>
          <%= form.text_area :comment,id:"l1",placeholder:"意見を入力",class:"form-control" %>
          <%= hidden_field_tag :answer_id, @answer.id %>
          <%= form.submit "意見を投稿", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>


<div class="col-lg-12">
  <div class="row">
    <table class="table table-stripe">
      <% @comments.each do |comment| %>
      <tr>
        <th class="info" width="20%">
          <div class="circle">
            <% if comment.answer.user.uid.nil? %>
            <%= attachment_image_tag comment.answer.user, :profile_image,　class:"img-circle", fallback: "no_image.jpg", size:'200x200'%>
            <% else %>
            <%= image_tag comment.answer.user.image_origin, size:'200x200' %>
            <% end %>
          </div>
          <span><%= comment.answer.user.name %>：<%= comment.answer.selection.name_i18n %></span>
        </th>
        <td>
          <small>Comment</small>
          <p><%= comment.comment %></p>
          <small
            style="position:relative; margin-right:0px;">投稿日時：<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></small>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>